common: &common
  endpoint: 'http://www.subscriptus.co'
  key: '$P$B2CNRpY/MCdmoNenQKrtdRyD8H8LG9.'
  
development:
  endpoint: 'http://localhost:3000/login_connector'
  <<: *common
test:
  <<: *common
  key: 'testkey'
staging:
  <<: *common
  endpoint: 'http://www.subscriptus.co/loginConnector.php'
production:
  <<: *common
