common: &common
  endpoint: 'http://www.crikey.com.au/loginconnector.php'
  key: '$P$B2CNRpY/MCdmoNenQKrtdRyD8H8LG9.'
  
development:
  <<: *common
test:
  <<: *common
  key: 'testkey'
production:
  <<: *common
